spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: ${MONGODB_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always